# Generated by Django 3.1 on 2020-08-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickGIFs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=36, unique=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('gif_file', models.ImageField(upload_to='quick_gifs/')),
                ('sharable', models.BooleanField(default=False)),
            ],
        ),
    ]
